apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gpqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-gpqe
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-gpqe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gpqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gpqe
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-dlfk-tenant/dotnet-component/devfile-sample-dotnet60-basic-gpqe@sha256:4ca65af743dc90b5f210b74b746670e7835d43aee33afd60f905fda416e3bb1f
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
