apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-gpqe
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-dlfk-tenant/dotnet-component/devfile-sample-dotnet60-basic-gpqe@sha256:4ca65af743dc90b5f210b74b746670e7835d43aee33afd60f905fda416e3bb1f
        name: main
        resources: {}
status: {}
